# Generated by Django 4.1 on 2023-01-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_category_customer_customer_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactLog',
        ),
    ]
