# Generated by Django 4.1 on 2023-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_contact_contactlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
